// This file is generated by icon spritesheet generator

export const iconNames = [
  "ArrowNarrowLeft",
  "Default",
  "Docker",
  "Dotnet",
  "Expo",
  "Flutter",
  "Godot",
  "Microsoft",
  "Mongodb",
  "MoonStars",
  "React",
  "RubyOnRails",
  "Sun",
  "Svelte",
  "Undefined",
] as const

export type IconName = typeof iconNames[number]
