// This file is generated by icon spritesheet generator

export const iconNames = [
  "ArrowNarrowLeft",
  "Default",
  "Dotnet",
  "Expo",
  "Flutter",
  "Godot",
  "React",
  "RubyOnRails",
  "Svelte",
] as const

export type IconName = typeof iconNames[number]
